/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnitest_demo_WYPFileManage */

#ifndef _Included_com_jnitest_demo_WYPFileManage
#define _Included_com_jnitest_demo_WYPFileManage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnitest_demo_WYPFileManage
 * Method:    splitFile
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnitest_1demo_WYPFileManage_splitFile
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_jnitest_demo_WYPFileManage
 * Method:    mergeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnitest_1demo_WYPFileManage_mergeFile
  (JNIEnv *, jclass, jstring,jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
