/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnitest_demo_CryptorUtil */

#ifndef _Included_com_jnitest_demo_CryptorUtil
#define _Included_com_jnitest_demo_CryptorUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnitest_demo_CryptorUtil
 * Method:    crypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnitest_1demo_CryptorUtil_crypt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_jnitest_demo_CryptorUtil
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnitest_1demo_CryptorUtil_decrypt
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
